version: '3.1'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=banco
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=230201
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    